#!/usr/bin/env bash

COMMAND="$1"
ARGUMENT="$2"

BOATDIR=$(dirname "$0")
PROJECTDIR=$(pwd)
USERCONFIGDIR="${HOME}/.longboat"
USERCONFIG="${USERCONFIGDIR}/config"

# Libs
# shellcheck source=lib/subroutines
source "${BOATDIR}/lib/subroutines" || error "Could not load ${BOATDIR}/lib/subroutines"

# Default Longboat configuration
# shellcheck source=etc/defaults.cfg
source "${BOATDIR}/etc/defaults.cfg" || error "Could not load ${BOATDIR}/etc/defaults.cfg"

# User configuration
if [ -f "${USERCONFIG}" ]; then
  # shellcheck disable=SC1090
  source "${USERCONFIG}"
fi

# Project configuration
if [ -f "${PROJECTDIR}/longboat.cfg" ]; then
  # shellcheck disable=SC1090
  source "${PROJECTDIR}/longboat.cfg"
fi

# Check for -h or --help
for HELPARG in "$@"; do
  case "${HELPARG}" in
  "-h")
    # shellcheck source=bin/help
    source "${BOATDIR}/bin/help" ; exit 0 ;;
  "--help")
    # shellcheck source=bin/help
    source "${BOATDIR}/bin/help" ; exit 0 ;;
  esac
done

case "${COMMAND}" in
"collect")
  # shellcheck source=bin/collect
  source "${BOATDIR}/bin/collect" ; exit $? ;;
"doctor")
  # shellcheck source=bin/doctor
  source "${BOATDIR}/bin/doctor" ; exit $? ;;
"inventory")
  # shellcheck source=bin/inventory
  source "${BOATDIR}/bin/inventory" ; exit $? ;;
"job")
  # shellcheck source=bin/job
  source "${BOATDIR}/bin/job" ; exit $? ;;
"init")
  # shellcheck source=bin/init
  source "${BOATDIR}/bin/init" ; exit $? ;;
"pull")
  # shellcheck source=bin/pull
  source "${BOATDIR}/bin/pull" ; exit $? ;;
"sshkey")
  # shellcheck source=bin/sshkey
  source "${BOATDIR}/bin/sshkey" ; exit $? ;;
"domain")
  # shellcheck source=bin/domain
  source "${BOATDIR}/bin/domain" ; exit $? ;;
"rr")
  # shellcheck source=bin/rr
  source "${BOATDIR}/bin/rr" ; exit $? ;;
"project")
  # shellcheck source=bin/project
  source "${BOATDIR}/bin/project" ; exit $? ;;
"env")
  # shellcheck source=bin/environment
  source "${BOATDIR}/bin/environment" ; exit $? ;;
"host")
  # shellcheck source=bin/host
  source "${BOATDIR}/bin/host" ; exit $? ;;
"droplet")
  # shellcheck source=bin/droplet
  source "${BOATDIR}/bin/droplet" ; exit $? ;;
"group")
  # shellcheck source=bin/group
  source "${BOATDIR}/bin/group" ; exit $? ;;
"auth")
  # shellcheck source=bin/auth
  source "${BOATDIR}/bin/auth" ; exit $? ;;
"upgrade")
  echo "==> Pulling latest version of Longboat CLI..."
  cd "${BOATDIR}" && git pull -q
  echo "==> ...done! We highly recommend running: boat doctor"
  ;;
*)
  # shellcheck source=bin/help
  source "${BOATDIR}/bin/help"
  exit 0
  ;;
esac
