#!/usr/bin/env bash

COMMAND="$1"
ARGUMENT="$2"

BOATDIR=`dirname $0`
PROJECTDIR=`pwd`

# Subroutines
source ${BOATDIR}/lib/subroutines || error "Could not load ${BOATDIR}/lib/subroutines"

# Default Longboat configuration
source ${BOATDIR}/etc/defaults.cfg || error "Could not load ${BOATDIR}/etc/defaults.cfg"

# User configuration
if [ -f "${HOME}/.longboat.cfg" ]; then
  source ${HOME}/.longboat.cfg
fi

# Project configuration
if [ -f "${PROJECTDIR}/longboat.cfg" ]; then
  source ${PROJECTDIR}/longboat.cfg
fi
if [ -z "${COMMAND}" ]; then
  boat_help
  exit 0
fi

case "${COMMAND}" in
"help")
  boat_help ; exit 0 ;;
"init")
  source ${BOATDIR}/bin/init || exit $?
  source ${BOATDIR}/bin/update || exit $?
  source ${BOATDIR}/bin/doctor || exit $?
  exit 0
  ;;
"update")
  source ${BOATDIR}/bin/update
  exit $?
  ;;
"doctor")
  source ${BOATDIR}/bin/doctor
  exit $?
  ;;
"inventory")
  source ${BOATDIR}/bin/inventory
  exit $?
  ;;
"host")
  source ${BOATDIR}/bin/host
  exit $?
  ;;
"sshkey")
  source ${BOATDIR}/bin/sshkey ; exit $? ;;
"sshkeys")
  source ${BOATDIR}/bin/sshkey ; exit $? ;;
"org")
  source ${BOATDIR}/bin/organization ; exit $? ;;
"organization")
  source ${BOATDIR}/bin/organization ; exit $? ;;
*)
  echo "ERROR! Unknown command. Try 'boat help' or the online documentation"
  echo "       for more information: ${LONGBOAT_DOCS}"
  exit 1
  ;;
esac

