#!/usr/bin/env bash

COMMAND="$1"
ARGUMENT="$2"

BOATDIR=`dirname $0`
PROJECTDIR=`pwd`

# Subroutines
source ${BOATDIR}/lib/subroutines || error "Could not load ${BOATDIR}/lib/subroutines"

# Default Longboat configuration
source ${BOATDIR}/etc/defaults.cfg || error "Could not load ${BOATDIR}/etc/defaults.cfg"

# User configuration
if [ -f "${HOME}/.longboat.cfg" ]; then
  source ${HOME}/.longboat.cfg
fi

# Project configuration
if [ -f "${PROJECTDIR}/longboat.cfg" ]; then
  source ${PROJECTDIR}/longboat.cfg
fi
if [ -z "${COMMAND}" ] || [ "${COMMAND}" == "help" ]; then
cat << ENDOFHELP
Usage: boat <command> [<args>]

  init        Initialize a new Longboat project
  update      Update project with latest config
  doctor      Check Longboat installation and project

Management commands:

  host        Manage hosts.
  sshkey      Manage your SSH keys.
  org         Manage your organizations.

Ansible commands:

  inventory   Get inventory from API. Used by ansible.

More information in the online documentation:
${LONGBOAT_DOCS}

ENDOFHELP
  exit 1
fi

case "${COMMAND}" in
"init")
  source ${BOATDIR}/bin/init || exit $?
  source ${BOATDIR}/bin/update || exit $?
  source ${BOATDIR}/bin/doctor || exit $?
  exit 0
  ;;
"update")
  source ${BOATDIR}/bin/update
  exit $?
  ;;
"doctor")
  source ${BOATDIR}/bin/doctor
  exit $?
  ;;
"inventory")
  source ${BOATDIR}/bin/inventory
  exit $?
  ;;
"host")
  source ${BOATDIR}/bin/host
  exit $?
  ;;
"sshkey")
  source ${BOATDIR}/bin/sshkey ; exit $? ;;
"sshkeys")
  source ${BOATDIR}/bin/sshkey ; exit $? ;;
"org")
  source ${BOATDIR}/bin/organization ; exit $? ;;
"organization")
  source ${BOATDIR}/bin/organization ; exit $? ;;
*)
  echo "ERROR! Unknown command. Try 'boat' or the online documentation"
  echo "       for more information: ${LONGBOAT_DOCS}"
  exit 1
  ;;
esac

