#!/usr/bin/env bash

function echo_json() {
  echo "$1" | jq .
}

function api_curl() {
  local ARGS=""
  local METHOD="$1"
  local URL="${LONGBOAT_ENDPOINT}/${LONGBOAT_API}$2"

  if [ $# -gt 2 ]; then
    for ARG in "${@:3}"; do
      ARGS="${ARGS} --data-urlencode ${ARG}"
    done
  fi

  CURL_TMP="/tmp/longboat.curl.$$"
  touch ${CURL_TMP}
  chmod 600 ${CURL_TMP}
  CURL_CODE=`curl -s -w "%{http_code}" -o "${CURL_TMP}" -H "Authorization: ${LONGBOAT_TOKEN}" ${ARGS} -X ${METHOD} "${URL}"`
  CURL_EXIT="$?"
  CURL_RESPONSE=`cat ${CURL_TMP}`
  rm ${CURL_TMP}

  if [ ${CURL_EXIT} -gt 0 ]; then
    echo "ERROR! API request failed - curl error code ${CURL_EXIT}"
    echo "For more information https://curl.haxx.se/libcurl/c/libcurl-errors.html"
    exit 1
  fi

  if [ -z ${CURL_SILENT} ]; then
    echo_json "${CURL_RESPONSE}"
  fi
}

function boat_help() {
cat << ENDOFHELP
Usage: boat <command> [<args>]

  upgrade     Pull latest version of CLI tools
  doctor      Check Longboat installation and project
  update      Update current project with latest config

User commands:

  sshkey      Manage your SSH keys.

Organization commands:

  org         Manage your organizations.
  project     Manage projects.
  domain      Manage domains.
  rr          Manage dns records for domains.

Project commands:

  host        Manage hosts.
  env         Manage environments

Ansible commands:

  inventory   Get inventory from API. Used by ansible.

More information in the online documentation:
${LONGBOAT_DOCS}

ENDOFHELP
}
